addons:
    apt:
        sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
            - cmake
            - cmake-data

language: c
compiler:
    - gcc-5.0

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
