
# Default sed regexp - multiline due to syntax constraints
define sed-y
    "/^->/{s:->#\(.*\):/* \1 */:; \
    s:^->\([^ ]*\) [\$$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:; \
    s:^->\([^ ]*\) [\$$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; \
    s:->::; p;}"
endef

define offsets
    (set -e; \
     echo "#ifndef __ASM_OFFSETS_H__"; \
     echo "#define __ASM_OFFSETS_H__"; \
     echo "/*"; \
     echo " * DO NOT MODIFY."; \
     echo " *"; \
     echo " * This file was generated by kernel.mk from linux-3.17/Kbuild"; \
     echo " *"; \
     echo " */"; \
     echo ""; \
     sed -ne $(sed-y) $(out_dir)/asm-offsets.s; \
     echo ""; \
     echo "#endif" ) > $@
endef

define version
	(set -e;\
		echo "#ifndef __VERSION_H__";\
		echo "#define __VERSION_H__";\
		echo "#define KERNEL_VERSION \"$(shell date +%y\/%m\/%d-%H:%M:%S)\"";\
		echo "#endif";\
	) > $@
endef
 
version.h :
	$Q $(version)  

$(out_dir)/asm-offsets.h : asm-offsets.def object.h task.h
	$Q cp $< $(out_dir)/asm-offsets.c
	$Q $(CC) -S $(out_dir)/asm-offsets.c -I./ $(c_flags) -o $(out_dir)/asm-offsets.s
	$Q $(offsets)
c_flags += -I$(out_dir)
x86.S : $(out_dir)/asm-offsets.h

main.c : version.h
