#!/bin/sh
sed_y='/^->/{s:->#\(.*\):/* \1 */:;
    s:^->\([^ ]*\) [$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:;
    s:^->\([^ ]*\) [$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:;
    s:->::; p;}'
offsets()
{
    set -e
    echo "#ifndef __ASM_OFFSETS_H__"
    echo "#define __ASM_OFFSETS_H__"
    echo "/*"
    echo " * DO NOT MODIFY."
    echo " *"
    echo " * This file was generated by kernel.mk from linux-3.17/Kbuild"
    echo " *"
    echo " */"
    echo ""
    sed -ne "$sed_y" $1
    echo ""
    echo "#endif"
}

offsets $1 > $2
